apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: microservice
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-podlogs
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - namespaces # <<< MISSING IN YOUR CURRENT FILE
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-podlogs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-podlogs
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: microservice
