apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: microservice
data:
  SPRING_APP_NAME: "gateway-service"
  SERVER_PORT: "8085"

  # Redis (for rate-limiting)
  SPRING_DATA_REDIS_HOST: "redis.microservice.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"

  # Logging
  LOG_LEVEL_GATEWAY: "INFO"
  LOG_LEVEL_CORS: "DEBUG"
  LOG_LEVEL_SECURITY: "DEBUG"

  # CORS
  CORS_ALLOWED_ORIGINS: "http://ui.microservice.svc.cluster.local"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"
