apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice
  namespace: microservice
  labels:
    app: configservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice
  template:
    metadata:
      labels:
        app: configservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        # -----------------------
        # CONFIG SERVICE CONTAINER
        # -----------------------
        - name: app
          image: ${IMAGE_REPO}/new-ms-config-service:${IMAGE_VERSION}
          ports:
            - containerPort: 8888
              name: http
          envFrom:
            - configMapRef:
                name: microservice-app-settings
            - configMapRef:
                name: app-config  # <--- ONLY env override, NOT mounted
          env:
            - name: SPRING_APP_NAME
              value: config-service
            - name: SERVER_PORT
              value: "8888"
            - name: OTEL_SERVICE_NAME
              value: configservice

      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
---
apiVersion: v1
kind: Service
metadata:
  name: configservice
  namespace: microservice
  labels:
    app: configservice
spec:
  selector:
    app: configservice
  ports:
    - name: http
      port: 8888
      targetPort: http
  type: ClusterIP

