apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice
  labels:
    app: customerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerservice
  template:
    metadata:
      labels:
        app: customerservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: app
          image: $IMAGE_REPO/new-ms-customer-service:$IMAGE_VERSION
          ports:
            - containerPort: 8081
              name: http
          envFrom:
            - configMapRef:
                name: microservice-app-settings
          env:
            - name: SPRING_APP_NAME
              value: customer-service
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_ACTIVE_PROFILE
              value: gcp
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: OTEL_SERVICE_NAME
              value: customerservice
        - name: alloy
          image: grafana/alloy:main
          args: ["run", "/etc/alloy/alloy.alloy"]
          env:
            - name: ALLOY_ENABLE_FEATURES
              value: flow
          ports:
            - name: otlp-http
              containerPort: 4318
            - name: otlp-grpc
              containerPort: 4317
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: customerservice
  labels:
    app: customerservice
spec:
  selector:
    app: customerservice
  ports:
    - name: http
      port: 8081
      targetPort: http
  type: ClusterIP
