apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-ingress
  namespace: microservice
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 80
          - path: /api/customer
            pathType: Prefix
            backend:
              service:
                name: customerservice
                port:
                  number: 8080
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: reactiveorderservice
                port:
                  number: 8080
          - path: /gateway
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
          - path: /eureka
            pathType: Prefix
            backend:
              service:
                name: discovery
                port:
                  number: 8761
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: configservice
                port:
                  number: 8888

