apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kafka-from-microservice
  namespace: kafka
spec:
  podSelector:
    matchLabels:
      strimzi.io/kind: Kafka
      strimzi.io/cluster: my-cluster
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: microservice
      ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9091
        - protocol: TCP
          port: 9090
