apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discovery-ui-ingress
  namespace: microservice
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /discovery/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: discovery
                port:
                  number: 8761
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discovery-ingress
  namespace: microservice
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/eureka/$2"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /eureka(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: discovery
                port:
                  number: 8761
