apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice
  namespace: microservice
  labels:
    app: configservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice
  template:
    metadata:
      labels:
        app: configservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: app
          image: ${IMAGE_REPO}/new-ms-config-service:${IMAGE_VERSION}
          ports:
            - containerPort: 8888
              name: http
          envFrom:
            - configMapRef:
                name: microservice-app-settings
            - configMapRef:
                name: configservice-config
          env:
            - name: SPRING_CONFIG_IMPORT
              value: ""
            - name: OTEL_SERVICE_NAME
              value: configservice
        # -----------------------
        # ALLOY SIDECAR
        # -----------------------
        - name: alloy
          image: grafana/alloy:latest
          args:
            [
              "run",
              "--stability.level=public-preview",
              "/etc/alloy/alloy.alloy",
            ]
          env:
            - name: ALLOY_ENABLE_FEATURES
              value: flow
          ports:
            - name: otlp-http
              containerPort: 4318
            - name: otlp-grpc
              containerPort: 4317
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log

      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: configservice
  namespace: microservice
  labels:
    app: configservice
spec:
  selector:
    app: configservice
  ports:
    - name: http
      port: 8888
      targetPort: http
  type: ClusterIP
